services:
  - type: web
    name: lunch-app-frontend
    env: static
    buildCommand: ./render-build.sh
    staticPublishPath: ./frontend/build
    routes:
      - type: rewrite
        source: /*
        destination: /index.html